version: '3.4'

services:
    influxdb:
        image: influxdb:latest
        container_name: logmetrics-influxdb
        hostname: logmetricsinfluxdb
        restart: always
        volumes:
            - D:/DockerData/influxdb:/var/lib/influxdb
        networks:
            - logmetrics-network
        ports:
            - 8086:8086
        environment:
            - TZ=Asia/Ho_Chi_Minh
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=loipv
            - DOCKER_INFLUXDB_INIT_PASSWORD=234fdswe65
            - DOCKER_INFLUXDB_INIT_ORG=logmetrics
            - DOCKER_INFLUXDB_INIT_BUCKET=logmetrics
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=logmetricsinfluxdb
            - ApplicationId=logmetrics-influxdb

    telegraf:
        image: telegraf:latest
        container_name: logmetrics-telegraf
        hostname: logmetricstelegraf
        restart: always
        build:
            context: .
            dockerfile: telegraf/Dockerfile
        depends_on:
            - "influxdb"
        networks:
            - logmetrics-network
        environment:
            - TZ=Asia/Ho_Chi_Minh
            - ApplicationId=logmetrics-telegraf

    grafana:
        image: grafana/grafana:latest
        container_name: logmetrics-grafana
        hostname: logmetricsgrafana
        restart: always
        volumes:
            - D:/DockerData/grafana:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_USER=loipv
            - GF_SECURITY_ADMIN_PASSWORD=234fdswe65
            - GF_USERS_ALLOW_SIGN_UP=false
            - GF_SMTP_ENABLED=true
            - GF_SMTP_HOST=smtp.gmail.com:587
            - GF_SMTP_USER=vanloi@quangich.com
            - GF_SMTP_PASSWORD=quangich123
            - GF_SMTP_FROM_ADDRESS=vanloi@quangich.com
            - TZ=Asia/Ho_Chi_Minh
            - ApplicationId=logmetrics-grafana
        networks:
            - logmetrics-network
        ports:
            - 3000:3000
        depends_on:
            - "influxdb"

networks:
    logmetrics-network:
        name: logmetrics-network
        driver: bridge